### ISSUE TITLE
Code ?

### ISSUE THREAD

**Issue by cYrAx157** [cr-api/cr-api#114]
Why don´t you upload your code, so we can contribute and support you ?
It would be better if we work together.

That is also the meaning of Github

~ cYrAx

**Comment by selfish** [comment]
@cYrAx157 - thanks for your message. Honest answer?
Firstly, I don't believe this is the meaning of github.
This is, if anything, the social, open-source, part of github.

As for getting support, we'd love that, but how can we assure that the project isn't just stolen?
We are actively seeking working hands, but it seems like what we have asked from anyone who offered help wasn't appealing: support the game data area.

It looks like anyone who offered to help, aside from one or two aho are in our collaboration forum, is now ignoring me after I didn't share the code.

Heck, I wrote so many APIs for a living. I don't need help in improving the api side. This is where I'm the authority and the professional. We need help obtaining more data that can be served over that API.

So no, I'm not interested in pull requests to the API. I'm interested in decoded packets. And those you can do without access to my code.

Do you know what else? We're the only ones serving millions a month, with realtime data. Sadly, we have high error rates because I'm not the best reverse engineer out there. But I managed to create a great infrastructure that can serve ten-fold that, if only my communication with the game was better.

So here's the deal: We will keep paying for the servers that bring you this data. @smlbiobot and myself are the only ones out there who do what we do without profit. We were truely hoping for this to be used by the community in ways that will improve all of our lives. But it didn't happen, and the greatest thing to come out from our api, was cr-api.com, which was created by SML alone.

As said, we'll keep paying the bills for everyone. I'm even happy to. But instead of trying to peek at my code (and that's not directed at you personally, but towards many who offered help and went away as soon as I asked for what I really need), help in what's really needed, which can be done using tools that are public right now.

And just to explain, not exposing the code will save me, personally, hours of work to hide keys and otherwise secure my very-conveniently-private repo. Hours that can be invested in getting even lower response times, or even a new stat on you profile.

**Comment by cYrAx157** [comment]
okay thanks for your honest answer.
Just to get sure: I appreciate your work and the hours you left developing.
But why do you think your code is "just stolen" ?
Do you think Linux is stolen, just by setting it open-source ?
The opposite is the case, the code got better and better, only because of shared development.
I understand the people who do not just want to decode packages, they do not want to work for you, they want to work with you.
Don't get me wrong, I don't want your code, I just want you to show the other side.
Thats just my personal opinion: Using Github, just as an issue tracker is wrong, but as I said, my personal opinion.

I wish you many luck, and thanks for your work.

**Comment by Xzlash** [comment]
GitHub has private repositories for a reason, if GittHub was intended to be *completely* open-source and collaborative, why would they have these? Also, if you want to help with packets, make sure to check out https://github.com/royale-proxy
